[build-system]
requires = ["setuptools >= 38.0.0",
            "setuptools_scm >= 2.0.0",
            "wheel"]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
addopts = "--cov=poke"
testpaths = [
    "tests",
]